on:
  push:
    branches:
      - main
      - 'feature/**'
  build:
    needs: information
    runs-on: devops-shack
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
